### ISSUE TITLE
Checking the code of the assignment_1

### ISSUE THREAD

**Issue by Gretadelnista** [lucabaldini/cmepda#3]
Salve, volevo chiederle se cortesemente può dare un'occhiata al mio codice ed evidenziarmi la presenza di anti-pattern o suggerirmi degli improvement.

LINK source-code: https://github.com/Gretadelnista/cmepda/blob/master/assignment_basic_1.py

Ho fatto in modo che l'utente possa settore il livello di severità del Logging dalla Command-line (per default INFO): così facendo, mi sono resa conto che nel caso in cui l'utente scelga DEBUG, vengono stampati dei messaggi di debug relativi alla parte di codice con cui viene realizzato l'istogramma delle frequenze ( è necessario richiedere che venga realizzato l'istogramma con l'opzione -hist yes). Questi, tuttavia, non sono stati definiti all'interno del codice, ma sembrano relativi a matplotlib.
Può fornirmi una qualche spiegazione di ciò? Magari possiamo riparlarne anche a voce.
Cordiali Saluti
Greta Del Nista

**Comment by lucabaldini** [comment]
Thanks!
https://github.com/Gretadelnista/cmepda/issues/4
