### ISSUE TITLE
Conteggio parole errato nella bozze di assegnamento 1

### ISSUE THREAD

**Issue by damides** [lucabaldini/cmepda#4]
Il file viene letto usando il metodo `read()`, questo crea una mega stringa che contiene pero' anche il newline character `\n`, questo fa sia erroneamente contato il numero di n.

**Comment by lucabaldini** [comment]
Why are you saying this?
```
Python 3.7.4 (default, Jul  9 2019, 16:32:37) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 'n' in 'Hanna'
True
>>> 'n' in '\n\n\n\n\n'
False
>>> 'n' == '\n'
False
>>> 
```

**Comment by damides** [comment]
Verissimo, mi sono confuso non avendo contato che con l'escape il carattere viene saltato a pie' pari. 
Grazie!
